version: '3'

services:
    db:
        image: postgres
        container_name: coopedin-db
        restart: unless-stopped
        env_file:
            - database.env
        volumes:
            - ./config/:/var/lib/postgresql/data/
        ports:
            - '5432:5432'

    adminer:
        image: adminer
        container_name: coopedin-adminer
        restart: unless-stopped
        ports:
            - 8080:8080
